# compose.yaml
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports: ["3306:3306"]
    volumes: 
      - db_data:/var/lib/mysql
      - ./medapp.sql:/docker-entrypoint-initdb.d/medapp.sql  # Auto-runs on first start
      - ./medapp.sql:/sql/medapp.sql  # Also available for manual re-runs
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile-httpd-php
    # Use the apache-based image built by Dockerfile-httpd-php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend:cached
    # Let the image's default CMD start Apache; don't override with php -S
    ports: ["8080:80"]        # map host 8080 -> container 80 (Apache)
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
