version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    container_name: php
    restart: unless-stopped
    environment:
      APP_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    container_name: web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - php
    # no volumes in production; the built assets are baked into the image

volumes:
  db_data:
